<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net452</TargetFramework>
    <LangVersion>7.3</LangVersion>
    <OutputType>Library</OutputType>
    <AssemblyName>CBPSMenu.Server.net</AssemblyName>
    <RootNamespace>CBPSMenu.Server</RootNamespace>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <OutputPath>../../dist/</OutputPath>
    <DefineConstants>SERVER</DefineConstants>
    <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
    <NoWarn>$(NoWarn);NU1903</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="..\Shared\**\*.cs" />
    <Compile Remove="..\Shared\ThemeManager.cs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="CitizenFX.Core.Server" Version="1.0.20150" />
    <PackageReference Include="Newtonsoft.Json" Version="12.0.3" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="Microsoft.CSharp" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="mscorlib" />
    <Reference Include="System" />
    <Reference Include="System.Core" />
  </ItemGroup>

  <Target Name="PostBuild" AfterTargets="PostBuildEvent">
    <Exec Command="cp &quot;$(TargetDir)$(TargetName).dll&quot; &quot;$(ProjectDir)../../$(TargetName).dll&quot;" />
    <Exec Command="cp &quot;$(TargetDir)Newtonsoft.Json.dll&quot; &quot;$(ProjectDir)../../Newtonsoft.Json.dll&quot;" />
  </Target>

</Project>
