<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net452</TargetFramework>
    <AssemblyName>CBPSMenu.Server.net</AssemblyName>
    <OutputType>Library</OutputType>
    <OutputPath>../../dist/</OutputPath>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <LangVersion>latest</LangVersion>
    <DefineConstants>SERVER</DefineConstants>
    <RootNamespace>CBPSMenu.Server</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="CitizenFX.Core.Server" Version="1.0.10230" />
  </ItemGroup>

  <ItemGroup>
    <Compile Include="../Shared/**/*.cs" LinkBase="Shared" />
  </ItemGroup>
</Project>
