<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net452</TargetFramework>
    <AssemblyName>CBPSMenu.net</AssemblyName>
    <OutputType>Library</OutputType>
    <OutputPath>../dist/Client/</OutputPath>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <LangVersion>latest</LangVersion>
    <RootNamespace>CBPSMenu.Client</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="CitizenFX.Core.Client" Version="1.0.7161" />
    <PackageReference Include="LemonUI.FiveM" Version="2.2.0" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
  </ItemGroup>

  <ItemGroup>
    <Compile Include="Shared/**/*.cs" LinkBase="Shared" />
  </ItemGroup>

  <!-- Copy dependencies to dist folder -->
  <Target Name="CopyDependencies" AfterTargets="Build">
    <Copy SourceFiles="$(OutputPath)LemonUI.FiveM.dll" DestinationFolder="../dist/lib/" SkipUnchangedFiles="true" />
    <Copy SourceFiles="$(OutputPath)Newtonsoft.Json.dll" DestinationFolder="../dist/lib/" SkipUnchangedFiles="true" />
  </Target>
</Project>
