<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net452</TargetFramework>
    <LangVersion>7.3</LangVersion>
    <OutputType>Library</OutputType>
    <AssemblyName>CBPSMenu.net</AssemblyName>
    <RootNamespace>CBPSMenu</RootNamespace>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <OutputPath>../dist/</OutputPath>
    <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Server\**" />
    <Compile Remove="CBPSMenu.Server\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="CitizenFX.Core.Client" Version="1.0.6985" />
    <PackageReference Include="LemonUI.FiveM" Version="2.1.1" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.1" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="Microsoft.CSharp" />
  </ItemGroup>

  <Target Name="PostBuild" AfterTargets="PostBuildEvent">
    <Exec Command="cp &quot;$(TargetDir)$(TargetName).dll&quot; &quot;$(ProjectDir)../$(TargetName).dll&quot;" />
    <Exec Command="cp &quot;$(TargetDir)Newtonsoft.Json.dll&quot; &quot;$(ProjectDir)../Newtonsoft.Json.dll&quot;" />
    <Exec Command="cp &quot;$(TargetDir)LemonUI.FiveM.dll&quot; &quot;$(ProjectDir)../LemonUI.FiveM.dll&quot;" />
  </Target>

</Project>
